import { PrismaClient, Spell } from '@prisma/client';
import { CharacterService } from './../services/CharacterService';
import { mockDeep } from 'jest-mock-extended'; 
import { UserService } from './../services/UserService'; // Importa o UserService

// Mock do Prisma Client
const prismaMock = mockDeep<PrismaClient>();

describe('Character Service', () => {
    let characterService: CharacterService;
    let userServiceMock: ReturnType<typeof mockDeep<UserService>>;

    beforeAll(() => {
        userServiceMock = mockDeep<UserService>();
        characterService = new CharacterService();
        characterService.prismaClient = prismaMock;
    });
    describe('create a new Character', () => {
        it('should create a new character for a user', async () => {
            const id = 1;
            const spellLevelMock1 = {
                spells: [{ id }] as Spell[],
                id: id,
                usedSpells: 0,
                totalSpells: 0,
            }
            const body = {  
                id: 1,
                name: "Nozit",
                playerName: "Rafael",
                class: "Ladino",
                level: 1,
                attributeId: id,
                savingThrowId: id,
                abilityCheckId: id,
                background: "Outlander",
                race: "Elfo negro",
                attributes: {
                    id: 1,
                    strengthValue: 10,
                    strengthMod: 0,
                    dexterityValue: 14,
                    dexterityMod: 2,
                    constitutionValue: 12,
                    constitutionMod: 1,
                    intelligenceValue: 8,
                    intelligenceMod: -1,
                    wisdomValue: 16,
                    wisdomMod: 3,
                    charismaValue: 18,
                    charismaMod: 4,
                },
                armorClass: 10,
                initiative: 3,
                failCounter: 0,
                successCounter: 0,
                speed: 30,
                hitPointsActual: 10,
                hitPointsMax: 15,
                alignment: "good Lawful",
                lifeDie: "1d8",
                totalLifeDie: "5d8",
                XP: 1000,
                bonds: "family",
                inspiration: true,
                proficiencyBonus: 2,
                temporaryHitPoints: 0,
                weapons: [],
                inventory: [],
                spellLevel0Id: id,
                spellLevel1Id: id,
                spellLevel2Id: id,
                spellLevel3Id: id,
                spellLevel4Id: id,
                spellLevel5Id: id,
                spellLevel6Id: id,
                spellLevel7Id: id,
                spellLevel8Id: id,
                spellLevel9Id: id,
                spellLevel0: spellLevelMock1,
                spellLevel1: spellLevelMock1,
                spellLevel2: spellLevelMock1,
                spellLevel3: spellLevelMock1,
                spellLevel4: spellLevelMock1,
                spellLevel5: spellLevelMock1,
                spellLevel6: spellLevelMock1,
                spellLevel7: spellLevelMock1,
                spellLevel8: spellLevelMock1,
                spellLevel9: spellLevelMock1,
                history: "História do Personagem",
                notes: "Notas Adicionais",
                abilityCheck: {
                    id,
                    acrobatics: 2,
                    animalHandling: 2,
                    arcana: 2,
                    athletics: 2,
                    deception: 2,
                    history: 2,
                    insight: 2,
                    intidimation: 2,
                    investigation: 2,
                    medicine: 2,
                    nature: 2,
                    perception: 2,
                    perfomance: 2,
                    persuasion: 2,
                    religion: 2,
                    sleightOfHand: 2,
                    stealth: 2,
                    survival: 2,
                },
                savingThrows: {
                    id,
                    strengthMod: 0,
                    dexterityMod: 2,
                    constitutionMod: 1,
                    intelligenceMod: -1,
                    wisdomMod: 5,
                    charismaMod: 6,
                },
                personalityTrait: "",
                ideals: "",
                weakness: "",
                talents: "",
                proficiency: "",
                conjurerClass: "",
                conjurerAttribute: "",
                spellCD: 0,
                spellAttackModifier: 0,
                photo: "",
                userId: id
            }
            const mockUser = {
                id: 1,
                password: "123456",
                username: "Rafael",
                email: 'test@example.com',
                isAdmin: false,
                characters: []
            };
            const mockUpdatedUser = {
                id: 1,
                password: "123456",
                username: "Rafael",
                email: 'test@example.com',
                isAdmin: false,
                characters: [{  
                    id: 1,
                    name: "Nozit",
                    playerName: "Rafael",
                    class: "Ladino",
                    level: 1,
                    attributeId: id,
                    savingThrowId: id,
                    abilityCheckId: id,
                    background: "Outlander",
                    race: "Elfo negro",
                    attributes: {
                        id: 1,
                        strengthValue: 10,
                        strengthMod: 0,
                        dexterityValue: 14,
                        dexterityMod: 2,
                        constitutionValue: 12,
                        constitutionMod: 1,
                        intelligenceValue: 8,
                        intelligenceMod: -1,
                        wisdomValue: 16,
                        wisdomMod: 3,
                        charismaValue: 18,
                        charismaMod: 4,
                    },
                    armorClass: 10,
                    initiative: 3,
                    failCounter: 0,
                    successCounter: 0,
                    speed: 30,
                    hitPointsActual: 10,
                    hitPointsMax: 15,
                    alignment: "good Lawful",
                    lifeDie: "1d8",
                    totalLifeDie: "5d8",
                    XP: 1000,
                    bonds: "family",
                    inspiration: true,
                    proficiencyBonus: 2,
                    temporaryHitPoints: 0,
                    weapons: [],
                    inventory: [],
                    spellLevel0Id: id,
                    spellLevel1Id: id,
                    spellLevel2Id: id,
                    spellLevel3Id: id,
                    spellLevel4Id: id,
                    spellLevel5Id: id,
                    spellLevel6Id: id,
                    spellLevel7Id: id,
                    spellLevel8Id: id,
                    spellLevel9Id: id,
                    spellLevel0: spellLevelMock1,
                    spellLevel1: spellLevelMock1,
                    spellLevel2: spellLevelMock1,
                    spellLevel3: spellLevelMock1,
                    spellLevel4: spellLevelMock1,
                    spellLevel5: spellLevelMock1,
                    spellLevel6: spellLevelMock1,
                    spellLevel7: spellLevelMock1,
                    spellLevel8: spellLevelMock1,
                    spellLevel9: spellLevelMock1,
                    history: "História do Personagem",
                    notes: "Notas Adicionais",
                    abilityCheck: {
                        id,
                        acrobatics: 2,
                        animalHandling: 2,
                        arcana: 2,
                        athletics: 2,
                        deception: 2,
                        history: 2,
                        insight: 2,
                        intidimation: 2,
                        investigation: 2,
                        medicine: 2,
                        nature: 2,
                        perception: 2,
                        perfomance: 2,
                        persuasion: 2,
                        religion: 2,
                        sleightOfHand: 2,
                        stealth: 2,
                        survival: 2,
                    },
                    savingThrows: {
                        id,
                        strengthMod: 0,
                        dexterityMod: 2,
                        constitutionMod: 1,
                        intelligenceMod: -1,
                        wisdomMod: 5,
                        charismaMod: 6,
                    },
                    personalityTrait: "",
                    ideals: "",
                    weakness: "",
                    talents: "",
                    proficiency: "",
                    conjurerClass: "",
                    conjurerAttribute: "",
                    spellCD: 0,
                    spellAttackModifier: 0,
                    photo: "",
                    userId: id
                }]
            }

            prismaMock.user.findUnique.mockResolvedValue(mockUser);

            prismaMock.user.update.mockResolvedValue(mockUpdatedUser);

            const result = await characterService.createCharacter(body, id);

            expect(result).toEqual(mockUpdatedUser);
            expect(prismaMock.user.findUnique).toHaveBeenCalledWith({
                where: { id: Number(id) }
            }); 
        })
    });
    describe("getOneCharacter", () => {
        it('should get one character of a user', async () => {
            const id = 1;
            const spellLevelMock1 = {
                spells: [{ id }] as Spell[],
                id: id,
                usedSpells: 0,
                totalSpells: 0,
            }
            const mockCharacter = {  
                id: 1,
                name: "Nozit",
                playerName: "Rafael",
                class: "Ladino",
                level: 1,
                attributeId: id,
                savingThrowId: id,
                abilityCheckId: id,
                background: "Outlander",
                race: "Elfo negro",
                attributes: {
                    id: 1,
                    strengthValue: 10,
                    strengthMod: 0,
                    dexterityValue: 14,
                    dexterityMod: 2,
                    constitutionValue: 12,
                    constitutionMod: 1,
                    intelligenceValue: 8,
                    intelligenceMod: -1,
                    wisdomValue: 16,
                    wisdomMod: 3,
                    charismaValue: 18,
                    charismaMod: 4,
                },
                armorClass: 10,
                initiative: 3,
                failCounter: 0,
                successCounter: 0,
                speed: 30,
                hitPointsActual: 10,
                hitPointsMax: 15,
                alignment: "good Lawful",
                lifeDie: "1d8",
                totalLifeDie: "5d8",
                XP: 1000,
                bonds: "family",
                inspiration: true,
                proficiencyBonus: 2,
                temporaryHitPoints: 0,
                weapons: [],
                inventory: [],
                spellLevel0Id: id,
                spellLevel1Id: id,
                spellLevel2Id: id,
                spellLevel3Id: id,
                spellLevel4Id: id,
                spellLevel5Id: id,
                spellLevel6Id: id,
                spellLevel7Id: id,
                spellLevel8Id: id,
                spellLevel9Id: id,
                spellLevel0: spellLevelMock1,
                spellLevel1: spellLevelMock1,
                spellLevel2: spellLevelMock1,
                spellLevel3: spellLevelMock1,
                spellLevel4: spellLevelMock1,
                spellLevel5: spellLevelMock1,
                spellLevel6: spellLevelMock1,
                spellLevel7: spellLevelMock1,
                spellLevel8: spellLevelMock1,
                spellLevel9: spellLevelMock1,
                history: "História do Personagem",
                notes: "Notas Adicionais",
                abilityCheck: {
                    id,
                    acrobatics: 2,
                    animalHandling: 2,
                    arcana: 2,
                    athletics: 2,
                    deception: 2,
                    history: 2,
                    insight: 2,
                    intidimation: 2,
                    investigation: 2,
                    medicine: 2,
                    nature: 2,
                    perception: 2,
                    perfomance: 2,
                    persuasion: 2,
                    religion: 2,
                    sleightOfHand: 2,
                    stealth: 2,
                    survival: 2,
                },
                savingThrows: {
                    id,
                    strengthMod: 0,
                    dexterityMod: 2,
                    constitutionMod: 1,
                    intelligenceMod: -1,
                    wisdomMod: 5,
                    charismaMod: 6,
                },
                personalityTrait: "",
                ideals: "",
                weakness: "",
                talents: "",
                proficiency: "",
                conjurerClass: "",
                conjurerAttribute: "",
                spellCD: 0,
                spellAttackModifier: 0,
                photo: "",
                userId: id
            }
            prismaMock.character.findUnique.mockResolvedValue(mockCharacter);

            const result = await characterService.getOneCharacter(1, 1);

            expect(result).toEqual(mockCharacter);
        })
    })
    describe("Get all characters", () => {
        it("should return all characters from a user",async () => {
            const id = 1;
            const spellLevelMock1 = {
                spells: [{ id }] as Spell[],
                id: id,
                usedSpells: 0,
                totalSpells: 0,
            }
            const spellLevelMock2 = {
                spells: [{ id: 2 }] as Spell[],
                id: 2,
                usedSpells: 0,
                totalSpells: 0,
            }
            const mockUser = { 
                id: 1,
                email: 'test12@example.com',
                password: '1234569',
                isAdmin: false,
                username: 'testuser9',
                characters: [
                {  
                id: 1,
                name: "Nozit",
                playerName: "Rafael",
                class: "Ladino",
                level: 1,
                attributeId: id,
                savingThrowId: id,
                abilityCheckId: id,
                background: "Outlander",
                race: "Elfo negro",
                attributes: {
                    id: 1,
                    strengthValue: 10,
                    strengthMod: 0,
                    dexterityValue: 14,
                    dexterityMod: 2,
                    constitutionValue: 12,
                    constitutionMod: 1,
                    intelligenceValue: 8,
                    intelligenceMod: -1,
                    wisdomValue: 16,
                    wisdomMod: 3,
                    charismaValue: 18,
                    charismaMod: 4,
                },
                armorClass: 10,
                initiative: 3,
                failCounter: 0,
                successCounter: 0,
                speed: 30,
                hitPointsActual: 10,
                hitPointsMax: 15,
                alignment: "good Lawful",
                lifeDie: "1d8",
                totalLifeDie: "5d8",
                XP: 1000,
                bonds: "family",
                inspiration: true,
                proficiencyBonus: 2,
                temporaryHitPoints: 0,
                weapons: [],
                inventory: [],
                spellLevel0Id: id,
                spellLevel1Id: id,
                spellLevel2Id: id,
                spellLevel3Id: id,
                spellLevel4Id: id,
                spellLevel5Id: id,
                spellLevel6Id: id,
                spellLevel7Id: id,
                spellLevel8Id: id,
                spellLevel9Id: id,
                spellLevel0: spellLevelMock1,
                spellLevel1: spellLevelMock1,
                spellLevel2: spellLevelMock1,
                spellLevel3: spellLevelMock1,
                spellLevel4: spellLevelMock1,
                spellLevel5: spellLevelMock1,
                spellLevel6: spellLevelMock1,
                spellLevel7: spellLevelMock1,
                spellLevel8: spellLevelMock1,
                spellLevel9: spellLevelMock1,
                history: "História do Personagem",
                notes: "Notas Adicionais",
                abilityCheck: {
                    id,
                    acrobatics: 2,
                    animalHandling: 2,
                    arcana: 2,
                    athletics: 2,
                    deception: 2,
                    history: 2,
                    insight: 2,
                    intidimation: 2,
                    investigation: 2,
                    medicine: 2,
                    nature: 2,
                    perception: 2,
                    perfomance: 2,
                    persuasion: 2,
                    religion: 2,
                    sleightOfHand: 2,
                    stealth: 2,
                    survival: 2,
                },
                savingThrows: {
                    id,
                    strengthMod: 0,
                    dexterityMod: 2,
                    constitutionMod: 1,
                    intelligenceMod: -1,
                    wisdomMod: 5,
                    charismaMod: 6,
                },
                personalityTrait: "",
                ideals: "",
                weakness: "",
                talents: "",
                proficiency: "",
                conjurerClass: "",
                conjurerAttribute: "",
                spellCD: 0,
                spellAttackModifier: 0,
                photo: "",
                userId: id
                }, 
                {  
                    id: 2,
                    name: "Nozit",
                    playerName: "Rafael",
                    class: "Ladino",
                    level: 1,
                    attributeId: id,
                    savingThrowId: id,
                    abilityCheckId: id,
                    background: "Outlander",
                    race: "Elfo negro",
                    attributes: {
                        id: 2,
                        strengthValue: 10,
                        strengthMod: 0,
                        dexterityValue: 14,
                        dexterityMod: 2,
                        constitutionValue: 12,
                        constitutionMod: 1,
                        intelligenceValue: 8,
                        intelligenceMod: -1,
                        wisdomValue: 16,
                        wisdomMod: 3,
                        charismaValue: 18,
                        charismaMod: 4,
                    },
                    armorClass: 10,
                    initiative: 3,
                    failCounter: 0,
                    successCounter: 0,
                    speed: 30,
                    hitPointsActual: 10,
                    hitPointsMax: 15,
                    alignment: "good Lawful",
                    lifeDie: "1d8",
                    totalLifeDie: "5d8",
                    XP: 1000,
                    bonds: "family",
                    inspiration: true,
                    proficiencyBonus: 2,
                    temporaryHitPoints: 0,
                    weapons: [],
                    inventory: [],
                    spellLevel0Id: 2,
                    spellLevel1Id: 2,
                    spellLevel2Id: 2,
                    spellLevel3Id: 2,
                    spellLevel4Id: 2,
                    spellLevel5Id: 2,
                    spellLevel6Id: 2,
                    spellLevel7Id: 2,
                    spellLevel8Id: 2,
                    spellLevel9Id: 2,
                    spellLevel0: spellLevelMock2,
                    spellLevel1: spellLevelMock2,
                    spellLevel2: spellLevelMock2,
                    spellLevel3: spellLevelMock2,
                    spellLevel4: spellLevelMock2,
                    spellLevel5: spellLevelMock2,
                    spellLevel6: spellLevelMock2,
                    spellLevel7: spellLevelMock2,
                    spellLevel8: spellLevelMock2,
                    spellLevel9: spellLevelMock2,
                    history: "História do Personagem",
                    notes: "Notas Adicionais",
                    abilityCheck: {
                        id:2,
                        acrobatics: 2,
                        animalHandling: 2,
                        arcana: 2,
                        athletics: 2,
                        deception: 2,
                        history: 2,
                        insight: 2,
                        intidimation: 2,
                        investigation: 2,
                        medicine: 2,
                        nature: 2,
                        perception: 2,
                        perfomance: 2,
                        persuasion: 2,
                        religion: 2,
                        sleightOfHand: 2,
                        stealth: 2,
                        survival: 2,
                    },
                    savingThrows: {
                        id: 2,
                        strengthMod: 0,
                        dexterityMod: 2,
                        constitutionMod: 1,
                        intelligenceMod: -1,
                        wisdomMod: 5,
                        charismaMod: 6,
                    },
                    personalityTrait: "",
                    ideals: "",
                    weakness: "",
                    talents: "",
                    proficiency: "",
                    conjurerClass: "",
                    conjurerAttribute: "",
                    spellCD: 0,
                    spellAttackModifier: 0,
                    photo: "",
                    userId: id
                }
                ]}

            userServiceMock.getOneUser.mockResolvedValue(mockUser);

            const result = await characterService.getAllCharacters(id);
            expect(result).toEqual(mockUser.characters);
            expect(userServiceMock.getOneUser).toHaveBeenCalledWith(Number(id));
        })
    })
})